package com.jarvis.app.latency

import com.jarvis.app.body.MemoryItem
import com.jarvis.app.body.MemoryStorePort
import com.jarvis.app.cognitive.CognitiveEngine
import com.jarvis.app.cognitive.UserModel
import com.jarvis.app.humancore.HumanCore
import com.jarvis.app.model.CognitiveAdmissionPolicy
import com.jarvis.app.model.FakeModelBackend
import com.jarvis.app.model.FakeResourceSnapshot
import com.jarvis.app.model.ModelBackend
import com.jarvis.app.model.ModelBackendConfig
import com.jarvis.app.model.ModelHandle
import com.jarvis.app.model.ModelManager
import com.jarvis.app.model.OrganRole
import com.jarvis.app.model.ResourceGovernor
import com.jarvis.app.model.ResourceSnapshot
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.filter
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withTimeout
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * REASONING-TIER-MODEL-GROUND-TRUTH-AND-WIRE — AC4: a real high-doubt turn
 * results in a generation call ACTUALLY SERVED BY THE REASONING TIER'S DISTINCT
 * MODEL, not degraded onto RESIDENT; a low-doubt turn stays on RESIDENT.
 *
 * Production call path driven here (exact same segment LatencyLayer wires):
 *
 *   LatencyLayer.bridgeSend (LatencyLayer.kt) -> ModelManager.send()
 *   -> CognitiveEngine admission gate (CognitiveAdmissionPolicy.serveTurn
 *      over the engine's REAL UncertaintyProfile) -> ModelManager.wake(
 *      REASONING) loads the distinct jarvis-reasoning handle -> the engine
 *      books that handle -> send() consumes the booking and generates from
 *      the handle (backend.generate -> its distinct modelId) instead of the
 *      active resident provider.
 *
 * The backend is a [FakeModelBackend] RECORDING every generation's
 * (handle.modelId, prompt, reply) so the proof pins WHICH model actually
 * answered. The resident tier (active provider) never routes through the
 * backend — so an empty/one-entry generation log is the honest contrast:
 * backend generations happen ONLY when the reasoning tier serves.
 */
class ReasoningTierServeGroundTruthTest {

    /**
     * Fake backend that records who answered each generation call. Uses an
     * inner [FakeModelBackend] for the lifecycle contract and adds a generation
     * log keyed by (handle.modelId, prompt, reply).
     */
    private class RecordingBackend : ModelBackend {
        data class Generation(val modelId: String, val prompt: String, val reply: String)
        val generations = mutableListOf<Generation>()

        private val fake = FakeModelBackend()
        val loadCount get() = fake.loadCount
        val unloadCount get() = fake.unloadCount
        val loaded: Set<ModelHandle> get() = fake.loaded

        override suspend fun loadModel(config: ModelBackendConfig): ModelHandle = fake.loadModel(config)

        override suspend fun generate(handle: ModelHandle, prompt: String): String {
            val reply = fake.generate(handle, prompt)
            generations += Generation(handle.modelId, prompt, reply)
            return reply
        }

        override suspend fun unloadModel(handle: ModelHandle) = fake.unloadModel(handle)

        override fun isLoaded(handle: ModelHandle): Boolean = fake.isLoaded(handle)
    }

    /** Deterministic empty in-memory [MemoryStorePort] — no Android, no disk. */
    private class EmptyMemoryStore : MemoryStorePort {
        override fun queryMemories(query: String, limit: Int): List<MemoryItem> = emptyList()
    }

    private suspend fun awaitReply(flow: StateFlow<String>, predicate: (String) -> Boolean): String =
        withTimeout(5_000) { flow.filter(predicate).first() }

    @Test
    fun `high-doubt turn is generated by the distinct reasoning model and low-doubt stays resident`(): Unit =
        runBlocking<Unit> {
            val backend = RecordingBackend()
            var nowMs = 0L
            var snapshot: ResourceSnapshot = FakeResourceSnapshot(
                availableMemoryMb = 8192,
                cpuLoadPercent = 5.0,
                thermalLevel = 0,
                batteryPercent = 100,
                isCharging = true
            )
            val mm = ModelManager(
                context = null,
                scope = CoroutineScope(Dispatchers.IO),
                backend = backend,
                resourceGovernor = ResourceGovernor(snapshotProvider = { snapshot }),
                cooldownMs = 1_000L,
                clock = { nowMs },
                autoSweep = false
            )
            val policy = CognitiveAdmissionPolicy()
            val engine = CognitiveEngine(
                scope = CoroutineScope(Dispatchers.IO),
                memoryStore = EmptyMemoryStore(),
                humanCore = HumanCore,
                modelManager = mm,
                cognitiveAdmissionPolicy = policy
            )
            engine.updateUserModel(UserModel(knownName = "Alice"))
            // The production bridge continuation: LatencyLayer wires
            // bridgeSend = modelManager.send.
            val bridgeSend: (String) -> Unit = { mm.send(it) }

            // Bootstrap the resident organ like production (anchor at boot).
            val resident = mm.wake(OrganRole.RESIDENT, task = "bootstrap")
            assertEquals("resident modelId resolves on the resident tier", "resident", resident.handle.modelId)

            // -----------------------------------------------------------------
            // (a) LOW-DOUBT turn stays on RESIDENT: no reasoning wake, no backend
            // generation — the active (resident) provider answers.
            // -----------------------------------------------------------------
            val low = engine.process(
                "I really enjoyed the concert last night.",
                sendBlock = bridgeSend
            )
            assertEquals(CognitiveEngine.TurnDecision.DIRECT_REPLY, low.decision)
            assertEquals(false, low.servedDegraded)
            val lowDoubt = policy.doubt(engine.cognitiveState.value.uncertainty)
            assertTrue("low-doubt turn is below threshold: $lowDoubt", lowDoubt < 0.5)
            val lowReply = awaitReply(mm.lastReply) { it.isNotBlank() }
            assertTrue(
                "resident turn answers via the provider (heuristic on JVM), not the backend: '$lowReply'",
                lowReply.contains("heuristic offline mode")
            )
            assertTrue("resident turn must not generate through the model backend", backend.generations.isEmpty())
            assertEquals("low-doubt turn never woke the reasoning organ", 1, backend.loadCount)

            // -----------------------------------------------------------------
            // (b) HIGH-DOUBT turn: admission wakes ON_DEMAND_REASONING (NOT
            // degraded) and the generation is served by the DISTINCT reasoning
            // model — recorded by the backend as the jarvis-reasoning handle.
            // -----------------------------------------------------------------
            val high = engine.process("Why did that happen this time?", sendBlock = bridgeSend)
            assertEquals(CognitiveEngine.TurnDecision.DIRECT_REPLY, high.decision)
            assertEquals(false, high.servedDegraded)
            val highDoubt = policy.doubt(engine.cognitiveState.value.uncertainty)
            assertTrue("high-doubt turn is at/above threshold: $highDoubt", highDoubt >= 0.5)

            val reasoningHandle = backend.loaded.first { it != resident.handle }
            assertEquals("reasoning wake loads the distinct model", "jarvis-reasoning:latest", reasoningHandle.modelId)
            assertEquals("resident + reasoning loads", 2, backend.loadCount)

            val reasoningReply = awaitReply(mm.lastReply) { it.contains("[fake-model-backend] echo:") }
            assertTrue(
                "the high-doubt reply self-identifies as backend output (fake echo), not the heuristic provider: '$reasoningReply'",
                reasoningReply.startsWith("[fake-model-backend] echo:")
            )
            assertEquals(
                "exactly ONE backend generation, and it was served by the jarvis-reasoning handle",
                1,
                backend.generations.size
            )
            val served = backend.generations.single()
            assertEquals("the distinct reasoning model answered the turn", "jarvis-reasoning:latest", served.modelId)
            assertEquals("the reasoning model answered THIS turn's payload", "Why did that happen this time?", served.prompt)
            assertTrue("answer carries the fake echo prefix (zero real model claimed)", served.reply.startsWith("[fake-model-backend] echo:"))

            // release() + cooldown sweep auto-unload the reasoning organ.
            nowMs += 5_000L
            mm.runCooldownSweep()
            assertFalse("cooldown auto-unload invalidates the reasoning handle", backend.isLoaded(reasoningHandle))

            // -----------------------------------------------------------------
            // (c) DEGRADED high-doubt turn: the governor DEGRADE_TO's the wake
            // onto RESIDENT — the reasoning handle must NOT serve, the resident
            // path answers, and the backend generation log does NOT grow.
            // -----------------------------------------------------------------
            snapshot = FakeResourceSnapshot(
                availableMemoryMb = 64,
                cpuLoadPercent = 90.0,
                thermalLevel = 2,
                batteryPercent = 80,
                isCharging = true
            )
            val degraded = engine.process("Why did that crash again?", sendBlock = bridgeSend)
            assertEquals(CognitiveEngine.TurnDecision.DIRECT_REPLY, degraded.decision)
            assertEquals(
                "governor DEGRADE_TO under pressure is flagged internally as degraded",
                true,
                degraded.servedDegraded
            )
            val degradedReply = awaitReply(mm.lastReply) { it.contains("heuristic offline mode") }
            assertTrue(
                "degraded turn answers via the resident provider path, not the reasoning model: '$degradedReply'",
                degradedReply.contains("heuristic offline mode")
            )
            assertEquals(
                "no reasoning-tier generation under pressure — the backend log does not grow",
                1,
                backend.generations.size
            )
            assertEquals("no second reasoning load under pressure", 2, backend.loadCount)

            // Final invariants: the resident tier is never auto-unloaded.
            assertTrue("the resident organ served the whole conversation and is still loaded", backend.isLoaded(resident.handle))
            assertFalse("reasoning stays unloaded at the end", backend.isLoaded(reasoningHandle))
        }
}